name: Deploy React Site
on:
  push:
    branches: [master] # push 到 master 分支时自动执行
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - setup-node:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run build # 生成 build 文件夹
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './build' 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4